// Builds the static pages (no dependencies).
//   node build.cjs          build once
//   node build.cjs --watch  rebuild when anything in src/ changes
//
// src/layout.html          the document shell: head, sprite, nav template, footer, modal, scripts
// src/partials/NAME.html   pulled in with <!-- @include NAME --> (in the layout or in a page)
// src/pages/**.html        one file per page; a front-matter block sets the layout values:
//                            ---
//                            title: Upload — Reclaim
//                            description: ...
//                            folder: platform        (which nav group is marked current)
//                            template: platform      (for page-specific motion)
//                            ---
// Output: src/pages/index.html -> index.html, src/pages/a/b.html -> a/b/index.html,
//         src/pages/a/index.html -> a/index.html (clean URLs: /a/b).
const fs = require('fs');
const path = require('path');

const root = __dirname;
const src = path.join(root, 'src');
const pagesDir = path.join(src, 'pages');

const esc = s => String(s).replace(/&(?!#?\w+;)/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// <!-- @include NAME --> or <!-- @include NAME key="value" ... --> (fills {{key}} inside the partial)
const include = (html, depth = 0) => html.replace(/<!--\s*@include\s+([\w-]+)((?:\s+[\w-]+="[^"]*")*)\s*-->/g, (_, name, args) => {
  if (depth > 8) throw new Error('include depth exceeded at ' + name);
  const file = path.join(src, 'partials', name + '.html');
  if (!fs.existsSync(file)) throw new Error('missing partial: ' + name);
  const params = {};
  for (const m of args.matchAll(/([\w-]+)="([^"]*)"/g)) params[m[1]] = m[2];
  const body = fs.readFileSync(file, 'utf8').replace(/\s+$/, '')
    .replace(/\{\{\s*([\w-]+)\s*\}\}/g, (m, k) => (k in params ? params[k] : m));
  return include(body, depth + 1);
});

const parse = text => {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text);
  const meta = {};
  if (m) m[1].split(/\r?\n/).forEach(line => {
    const i = line.indexOf(':');
    if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  });
  return { meta, body: m ? text.slice(m[0].length) : text };
};

const walk = dir => fs.readdirSync(dir, { withFileTypes: true }).flatMap(d =>
  d.isDirectory() ? walk(path.join(dir, d.name)) : d.name.endsWith('.html') ? [path.join(dir, d.name)] : []);

const build = () => {
  const t0 = Date.now();
  const layout = fs.readFileSync(path.join(src, 'layout.html'), 'utf8');
  const pages = walk(pagesDir);
  for (const file of pages) {
    const rel = path.relative(pagesDir, file).replace(/\\/g, '/');
    const { meta, body } = parse(fs.readFileSync(file, 'utf8'));
    const vars = { title: 'Reclaim', description: '', folder: '', template: '', ...meta };
    let html = include(layout)
      .replace('{{content}}', () => include(body).replace(/\s+$/, ''))
      .replace(/\{\{(\w+)\}\}/g, (_, k) => (k in vars ? esc(vars[k]) : ''));
    html = html.replace(/^<!doctype html>/i, `<!doctype html>\n<!-- generated by build.cjs from src/pages/${rel}; edit the source, then run: node build.cjs -->`);
    const out = rel === 'index.html' ? 'index.html'
      : rel.endsWith('/index.html') ? rel
      : rel.replace(/\.html$/, '/index.html');
    const target = path.join(root, out);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, html);
  }
  console.log(`built ${pages.length} pages in ${Date.now() - t0}ms`);
};

build();

if (process.argv.includes('--watch')) {
  let timer;
  fs.watch(src, { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(() => { try { build(); } catch (e) { console.error(e.message); } }, 80);
  });
  console.log('watching src/ ...');
}
